// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package rotation

import (
	"goframe-shop/api/backend/rotation"
)

type ControllerV1 struct{}

func NewV1() rotation.IRotationV1 {
	return &ControllerV1{}
}
